name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version numbers
        run: |
          # Extract version from release tag (e.g., v1.2.3 -> 1.2.3)
          VERSION=${GITHUB_REF_NAME#v}
          echo "Updating version to $VERSION"

          # Update version in package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json

          # Update version in system.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" public/system.json

      - name: Build with Vite
        run: npm run build

      - name: Copy files from public to dist
        run: cp -r public/* dist/

      - name: Create ZIP archive
        run: |
          cd dist
          zip -r ../fvtt-mds.zip .
          cd ..

      - name: Upload ZIP to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fvtt-mds.zip
          asset_name: fvtt-mds.zip
          asset_content_type: application/zip
